name: 'CI'

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Clean install
        run: npm ci

      - name: Tests
        run: npx mocha --reporter json > results.json

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: 'results.json'
          reporter: mocha-json
